# Generated by Django 5.0.6 on 2024-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSI_DUCK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeocenio',
            name='ocena',
            field=models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1')], default=0),
        ),
    ]
